In [254]:
import pandas as pd
#splitting the dataset into train and test
from sklearn.model_selection import train_test_split 

import torch
import torch.nn as nn  #Loss Functions, model
import torch.nn.functional as F   #activation function
from torch.autograd import Variable

In [255]:
# load IRIS dataset
dataset = pd.read_csv('D:\SANKHYANA\DataSets\Iris.csv')
dataset=dataset.rename(columns={"Species":"species"})
dataset=dataset.drop(["Id"],axis=1)

print(dataset)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]


In [256]:
# transform species to numerics
dataset.loc[dataset.species=='Iris-setosa', 'species'] = 0
dataset.loc[dataset.species=='Iris-versicolor', 'species'] = 1
dataset.loc[dataset.species=='Iris-virginica', 'species'] = 2

print(dataset["species"].dtype)

Species=[]
for i in dataset["species"]:
    Species.append(int(i))
    
dataset=dataset.drop(["species"],axis=1)
dataset["species"]=Species
print(dataset)

object
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]


In [257]:
train_X, test_X, train_y, test_y = train_test_split(dataset[dataset.columns[0:4]].values,
                                                    dataset.species.values, test_size=0.8)


# wrap up with Variable in pytorch
train_X = Variable(torch.from_numpy(train_X).float())
test_X = Variable(torch.from_numpy(test_X).float())
train_y = Variable(torch.from_numpy(train_y).long())
test_y = Variable(torch.from_numpy(test_y).long())

In [267]:
train_x

tensor([[6.3000, 3.3000, 4.7000, 1.6000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [4.8000, 3.1000, 1.6000, 0.2000],
        [6.3000, 2.8000, 5.1000, 1.5000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [7.2000, 3.2000, 6.0000, 1.8000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [5.7000, 2.9000, 4.2000, 1.3000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [6.1000, 2.8000, 4.0000, 1.3000],
        [6.5000, 3.2000, 5.1000, 2.0000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [6.4000, 2.8000, 5.6000, 2.2000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [5.5000, 3.5000, 1.3000, 0

In [268]:
train_y

tensor([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 2,
        0, 1, 0, 0, 2, 0])

In [258]:



class Net(nn.Module):
    # define nn
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, 100)
        self.fc2 = nn.Linear(100, 100)
        self.fc3 = nn.Linear(100, 3)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, X):
        X = F.relu(self.fc1(X))
        X = self.fc2(X)
        X = F.relu(X)
        X = self.fc3(X)
        X = self.softmax(X)

        return X
    


In [ ]:
net = Net()

In [ ]:
criterion = nn.CrossEntropyLoss()# cross entropy loss

optimizer = torch.optim.Adam(net.parameters(), lr=0.01)

In [259]:

for epoch in range(100):
    optimizer.zero_grad()
    out = net(train_X)
    loss = criterion(out, train_y)
    loss.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        print ('number of epoch', epoch, 'loss', loss.data)



number of epoch 0 loss tensor(1.0676)
number of epoch 10 loss tensor(0.6521)
number of epoch 20 loss tensor(0.5582)
number of epoch 30 loss tensor(0.5525)
number of epoch 40 loss tensor(0.5518)
number of epoch 50 loss tensor(0.5516)
number of epoch 60 loss tensor(0.5516)
number of epoch 70 loss tensor(0.5515)
number of epoch 80 loss tensor(0.5515)
number of epoch 90 loss tensor(0.5515)


In [260]:
test_pred_vals=net(test_X)
test_pred_vals

tensor([[2.1509e-08, 2.8665e-01, 7.1335e-01],
        [3.6742e-05, 9.9995e-01, 1.0247e-05],
        [9.9997e-01, 3.1822e-05, 1.2853e-24],
        [5.5495e-06, 9.9969e-01, 3.0556e-04],
        [2.9105e-10, 1.0384e-02, 9.8962e-01],
        [1.0693e-12, 6.1574e-04, 9.9938e-01],
        [1.3298e-06, 9.9989e-01, 1.0616e-04],
        [7.3643e-15, 1.4755e-04, 9.9985e-01],
        [2.1977e-12, 1.2372e-04, 9.9988e-01],
        [1.2891e-06, 9.9863e-01, 1.3649e-03],
        [3.8140e-05, 9.9996e-01, 7.4898e-07],
        [8.6822e-08, 5.8329e-01, 4.1671e-01],
        [1.0000e+00, 1.6080e-06, 1.2709e-30],
        [9.9999e-01, 1.3533e-05, 2.1422e-26],
        [9.9998e-01, 1.8518e-05, 2.0714e-25],
        [3.7421e-13, 5.1683e-05, 9.9995e-01],
        [9.9999e-01, 1.4823e-05, 4.4615e-26],
        [9.2005e-06, 9.9999e-01, 2.7831e-06],
        [8.6221e-08, 9.7246e-01, 2.7541e-02],
        [1.1827e-06, 9.9998e-01, 1.6079e-05],
        [1.0957e-12, 2.8795e-04, 9.9971e-01],
        [7.4398e-13, 1.8386e-04, 9

In [261]:
_, predict_y = torch.max(test_pred_vals, 1)

print('prediction accuracy', accuracy_score(test_y.data, predict_y.data))

prediction accuracy 0.975


In [266]:
print(predict_y)

tensor([2, 1, 0, 1, 2, 2, 1, 2, 2, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 2, 2, 0, 1,
        2, 1, 0, 0, 1, 1, 2, 0, 2, 2, 2, 0, 0, 2, 1, 2, 1, 1, 0, 1, 2, 0, 0, 1,
        0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1,
        0, 2, 0, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 1, 2, 0, 1,
        2, 1, 2, 2, 0, 2, 0, 0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 0])


In [270]:
from sklearn.metrics import classification_report
print(classification_report(predict_y,test_y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       0.95      0.98      0.97        43
           2       0.98      0.96      0.97        46

    accuracy                           0.97       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.97      0.98       120



In [271]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(predict_y,test_y))

[[31  0  0]
 [ 0 42  1]
 [ 0  2 44]]
