In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D,Dense,Activation,Flatten

In [3]:
model=Sequential()
model.add(Conv2D(32,(3,3), input_shape=(64,64,3),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,(3,3),activation="relu"))

In [4]:
model.add(Flatten())

In [5]:
model.add(Dense(32,input_shape=(64,64,3),activation="relu"))

In [6]:
model.add(Dense(64,activation="relu"))

In [7]:
model.add(Dense(7,activation="softmax"))

In [8]:
model.compile(loss="kullback_leibler_divergence",optimizer="sgd",metrics=["accuracy"])

In [9]:
from keras.preprocessing.image import ImageDataGenerator

In [10]:
train_images=ImageDataGenerator(rescale=1./255,shear_range=2,zoom_range=2)
test_images=ImageDataGenerator(rescale=1./255,shear_range=2,zoom_range=2)

In [11]:
train_data=train_images.flow_from_directory(r"E:\STIP TASKS\Traffic signals\train_data_traffic",
                                           target_size=(64,64),batch_size=32)
test_data=train_images.flow_from_directory(r"E:\STIP TASKS\Traffic signals\test_data_traffic",
                                          target_size=(64,64),batch_size=32)

Found 1046 images belonging to 7 classes.
Found 252 images belonging to 7 classes.


In [12]:
model.fit_generator(train_data,
                    validation_data=test_data,
                    epochs=5,
                    steps_per_epoch=1024,
                    validation_steps=252,verbose=1)


Epoch 1/5
1024/1024 [==============================] - 470s 459ms/step - loss: 0.6789 - accuracy: 0.7509 - val_loss: 0.5496 - val_accuracy: 0.7392
Epoch 2/5
1024/1024 [==============================] - 514s 502ms/step - loss: 0.2140 - accuracy: 0.9269 - val_loss: 1.4964 - val_accuracy: 0.7595
Epoch 3/5
1024/1024 [==============================] - 379s 370ms/step - loss: 0.1291 - accuracy: 0.9557 - val_loss: 0.9964 - val_accuracy: 0.7395
Epoch 4/5
1024/1024 [==============================] - 513s 501ms/step - loss: 0.0962 - accuracy: 0.9673 - val_loss: 0.5382 - val_accuracy: 0.7874
Epoch 5/5
1024/1024 [==============================] - 534s 522ms/step - loss: 0.0736 - accuracy: 0.9740 - val_loss: 0.7658 - val_accuracy: 0.8006


In [23]:
import numpy as np
import os
from keras.preprocessing import image
test_image = image.load_img(r"E:\STIP TASKS\Traffic signals\stop2_0_7458.jpg",target_size = (64, 64))
#test_image=image.load_img(r"E:\STIP TASKS\Traffic signals\test_green1.jpeg",target_size=(64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(train_data.class_indices)
print(result)

{'child_play_train': 0, 'go_train': 1, 'no_entry_train': 2, 'pedeatrian_train': 3, 'speed_lim_train': 4, 'stop_train': 5, 'yellow_train': 6}
[[0. 0. 0. 0. 0. 1. 0.]]


In [24]:

if int(result[0][0])== 1:
    print("go slow here, its school zone")
elif int(result[0][1])== 1:
    print("its green, go")
    
elif int(result[0][2])==1 :
    print(" no_entry")
elif int(result[0][4])== 1:
    print("stop or slow ahead, there is pedestrian_cross")
    
elif int(result[0][5])==1:
    print("stop")
    
elif int(result[0][6])==1:
    print("if your in moving stop here or move if your at starting position")

else:
    print("sorry, i am not recognized")

stop


In [25]:
import numpy as np
import os
from keras.preprocessing import image
#test_image = image.load_img(r"E:\STIP TASKS\Traffic signals\stop2_0_7458.jpg",target_size = (64, 64))
test_image=image.load_img(r"E:\STIP TASKS\Traffic signals\test_green1.jpeg",target_size=(64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(train_data.class_indices)
print(result)

{'child_play_train': 0, 'go_train': 1, 'no_entry_train': 2, 'pedeatrian_train': 3, 'speed_lim_train': 4, 'stop_train': 5, 'yellow_train': 6}
[[0. 1. 0. 0. 0. 0. 0.]]


In [26]:

if int(result[0][0])== 1:
    print("go slow here, its school zone")
elif int(result[0][1])== 1:
    print("its green, go")
    
elif int(result[0][2])==1 :
    print(" no_entry")
elif int(result[0][4])== 1:
    print("stop or slow ahead, there is pedestrian_cross")
    
elif int(result[0][5])==1:
    print("stop")
    
elif int(result[0][6])==1:
    print("if your in moving stop here or move if your at starting position")

else:
    print("sorry, i am not recognized")

its green, go


In [27]:
import numpy as np
import os
from keras.preprocessing import image
#test_image = image.load_img(r"E:\STIP TASKS\Traffic signals\stop2_0_7458.jpg",target_size = (64, 64))
test_image=image.load_img(r"E:\STIP TASKS\Traffic signals\child_at_play32.jpg",target_size=(64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(train_data.class_indices)
print(result)

{'child_play_train': 0, 'go_train': 1, 'no_entry_train': 2, 'pedeatrian_train': 3, 'speed_lim_train': 4, 'stop_train': 5, 'yellow_train': 6}
[[1. 0. 0. 0. 0. 0. 0.]]


In [28]:

if int(result[0][0])== 1:
    print("go slow here, its school zone")
elif int(result[0][1])== 1:
    print("its green, go")
    
elif int(result[0][2])==1 :
    print(" no_entry")
elif int(result[0][4])== 1:
    print("stop or slow ahead, there is pedestrian_cross")
    
elif int(result[0][5])==1:
    print("stop")
    
elif int(result[0][6])==1:
    print("if your in moving stop here or move if your at starting position")

else:
    print("sorry, i am not recognized")

go slow here, its school zone
